/** @type {import('tailwindcss').Config} */
export default {
  purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  content: [],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#3457dc",
          "primary-content": "#ffffff",
          "secondary": "#f6d860",
          "secondary-content": "#f6d860",
          "accent": "#37cdbe",
          "accent-content": "#37cdbe",
          "neutral": "#3d4451",
          "neutral-content": "#3d4451",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#d1d5db",
          "base-content": "#1f2937",
          "info": "#2094f3",
          "info-content": "#ffffff",
          "success": "#009485",
          "success-content": "#ffffff",
          "warning": "#ff9900",
          "warning-content": "#ffffff",
          "error": "#ff5724",
          "error-content": "#ffffff",
        },
        dark: {
          "primary": "#3457dc",
          "primary-content": "#ffffff",
          "secondary": "#f6d860",
          "secondary-content": "#f6d860",
          "accent": "#37cdbe",
          "accent-content": "#37cdbe",
          "neutral": "#3d4451",
          "neutral-content": "#3d4451",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#d1d5db",
          "base-content": "#1f2937",
          "info": "#2094f3",
          "info-content": "#ffffff",
          "success": "#009485",
          "success-content": "#ffffff",
          "warning": "#ff9900",
          "warning-content": "#ffffff",
          "error": "#ff5724",
          "error-content": "#ffffff",
        },
      },
    ],
    base: true,
    styled: true,
  },
}

